#!/bin/bash

. "${BASH_SOURCE%/*}/funcs.sh"

get_metadata() {
    mutagen-inspect "$1" | fgrep = | sort
}

cmp -s - <(get_metadata "$DIRNAME/obama.mp3") <<END
APIC=cover front,  (image/jpeg, 9833 bytes)
TALB=US State of the Union 2011
TCON=Spoken
TCOP=Public Domain
TDRC=2011-01-25
TIT2=The Internet [excerpt]
TLEN=6000
TPE1=Barack Obama
TPOS=0/0
TRCK=1/1
TSSE=MP3FS
END

cmp -s - <(get_metadata "$DIRNAME/raven.mp3") <<END
APIC=cover front,  (image/jpeg, 10226 bytes)
TALB=The Raven
TCON=Speech
TDRC=2007
TIT2=the_raven
TLEN=20970
TPE1=Edgar Allen Poe
TRCK=01
TSSE=MP3FS
END
