#!/bin/bash

. "${BASH_SOURCE%/*}/funcs.sh" "$1"

# Ensure log contains file sizes, predicted and actual
cat "$DIRNAME/obama.$DESTTYPE" > /dev/null
cat "$DIRNAME/raven.$DESTTYPE" > /dev/null

if [ "$DESTTYPE" == "mp4" ];
then
# mp4
echo Checking $DIRNAME/obama.mp4
SIZE=$(stat -c %s "$DIRNAME/obama.mp4")
echo Size: $SIZE
[ $SIZE -ge 99151 -a $SIZE -le 99676 ]
echo Checking $DIRNAME/raven.mp4
SIZE=$(stat -c %s "$DIRNAME/raven.mp4")
echo Size: $SIZE
[ $SIZE -ge 133661 -a $SIZE -le 133669 ]
elif [ "$DESTTYPE" == "mp3" ];
then
# mp3
echo Checking $DIRNAME/obama.mp3
SIZE=$(stat -c %s "$DIRNAME/obama.mp3")
echo Size: $SIZE
[ $SIZE -eq 96827 ]
echo Checking $DIRNAME/raven.mp3
SIZE=$(stat -c %s "$DIRNAME/raven.mp3")
echo Size: $SIZE
[ $SIZE -eq 126248 ]
else
exit 99
fi

