#!/bin/bash -e

cd "${BASH_SOURCE%/*}"

. ./check_format
. ./check_iwyu
. ./check_tidy
. ./check_guard

multidriver \
    format,check_format_single \
    iwyu,check_iwyu_single \
    tidy,check_tidy_single \
    guard,check_guard_single
