#!/usr/bin/env bash

set -e

cd "${BASH_SOURCE%/*}"

. ./check_format
. ./check_iwyu
. ./check_tidy
. ./check_guard
. ./check_incpath

CHECKS=(
    format,check_format_single
    guard,check_guard_single
    incpath,check_incpath_single
)

if [ "$1" != fast ] ; then
    CHECKS+=(
        iwyu,check_iwyu_single
        tidy,check_tidy_single
    )
fi

multidriver "${CHECKS[@]}"
